//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.18 at 04:24:18 PM EDT 
//


package com.java.training.boot.jaxb.schema.rq;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rq package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Fname_QNAME = new QName("", "fname");
    private final static QName _Lname_QNAME = new QName("", "lname");
    private final static QName _Id_QNAME = new QName("", "id");
    private final static QName _Age_QNAME = new QName("", "age");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rq
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EmployeeSearchRQ }
     * 
     */
    public EmployeeSearchRQ createEmployeeSearchRQ() {
        return new EmployeeSearchRQ();
    }



    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fname")
    public JAXBElement<String> createFname(String value) {
        return new JAXBElement<String>(_Fname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lname")
    public JAXBElement<String> createLname(String value) {
        return new JAXBElement<String>(_Lname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "id")
    public JAXBElement<BigInteger> createId(BigInteger value) {
        return new JAXBElement<BigInteger>(_Id_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "age")
    public JAXBElement<BigInteger> createAge(BigInteger value) {
        return new JAXBElement<BigInteger>(_Age_QNAME, BigInteger.class, null, value);
    }

}
