//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.18 at 04:23:32 PM EDT 
//


package com.java.training.boot.jaxb.schema.rs;

import com.java.training.boot.jaxb.schema.common.Address;
import com.java.training.boot.jaxb.schema.common.Employee;
import com.java.training.boot.jaxb.schema.common.Employees;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Zipcode_QNAME = new QName("", "zipcode");
    private final static QName _Fname_QNAME = new QName("", "fname");
    private final static QName _Country_QNAME = new QName("", "country");
    private final static QName _Lname_QNAME = new QName("", "lname");
    private final static QName _Phone_QNAME = new QName("", "phone");
    private final static QName _Id_QNAME = new QName("", "id");
    private final static QName _State_QNAME = new QName("", "state");
    private final static QName _Line2_QNAME = new QName("", "line2");
    private final static QName _Age_QNAME = new QName("", "age");
    private final static QName _Line1_QNAME = new QName("", "line1");
    private final static QName _Email_QNAME = new QName("", "email");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EmployeeSearchRS }
     * 
     */
    public EmployeeSearchRS createEmployeeSearchRS() {
        return new EmployeeSearchRS();
    }

    /**
     * Create an instance of {@link Employees }
     * 
     */
    public Employees createEmployees() {
        return new Employees();
    }

    /**
     * Create an instance of {@link Employee }
     * 
     */
    public Employee createEmployee() {
        return new Employee();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "zipcode")
    public JAXBElement<String> createZipcode(String value) {
        return new JAXBElement<String>(_Zipcode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "fname")
    public JAXBElement<String> createFname(String value) {
        return new JAXBElement<String>(_Fname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "country")
    public JAXBElement<String> createCountry(String value) {
        return new JAXBElement<String>(_Country_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "lname")
    public JAXBElement<String> createLname(String value) {
        return new JAXBElement<String>(_Lname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "phone")
    public JAXBElement<String> createPhone(String value) {
        return new JAXBElement<String>(_Phone_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "id")
    public JAXBElement<BigInteger> createId(BigInteger value) {
        return new JAXBElement<BigInteger>(_Id_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "state")
    public JAXBElement<String> createState(String value) {
        return new JAXBElement<String>(_State_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "line2")
    public JAXBElement<String> createLine2(String value) {
        return new JAXBElement<String>(_Line2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "age")
    public JAXBElement<BigInteger> createAge(BigInteger value) {
        return new JAXBElement<BigInteger>(_Age_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "line1")
    public JAXBElement<String> createLine1(String value) {
        return new JAXBElement<String>(_Line1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "email")
    public JAXBElement<String> createEmail(String value) {
        return new JAXBElement<String>(_Email_QNAME, String.class, null, value);
    }

}
